#!/bin/bash

export FAILURE_TARGET_CNT=2
export FAILURE_TARGET_USERS=(root root)
export FAILURE_TARGET_NAMES=(mdt0 ost2)
export FAILURE_TARGET_IPS=(192.168.56.110 192.168.56.112)
export FAILURE_TARGET_LNET_CARDS=(enp0s8 enp0s8)
export FAILURE_TARGET_MNT_PNT=(/mdt /ost)
export FAILURE_TARGET_LDISKFS_MNT_PNT=(/local /local)
export FAILURE_TARGET_DELETE_PCTG=10
export FAILURE_TARGET_CORRUPT_PCTG=10
export FAILURE_TARGET_CORRUPT_MAX_BITS=200
